name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb1-dev \
          libxrandr-dev \
          libxss-dev \
          libxcursor-dev \
          libxcomposite-dev \
          libasound2-dev \
          libxdamage-dev \
          libxext-dev \
          libxfixes-dev \
          libxi-dev \
          libxinerama-dev \
          libxkbcommon-dev \
          libxrender-dev \
          libxtst-dev \
          libxv-dev \
          libxxf86vm-dev \
          libegl1-mesa-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
